[default_config]
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
compiler = "zig"
diagnostics = true
default_diagnostics = true
compile_flags_txt = [
  "cc",
  "-x",
  "assembler-with-cpp",
  "-g",
  "-Wall",
  "-Wextra",
  "-pedantic",
  "-pedantic-errors",
  "-std=c2y",
  "-target",
  "x86_64-linux-musl",
]
